### ISSUE TITLE
brew create fails on 1.5.4

### ISSUE THREAD

**Issue by reda-alaoui** [Linuxbrew/docker#35]
Using version 1.5.4, create command does not work.

```
$ docker run linuxbrew/linuxbrew:1.5.4 brew create https://cdn.rawgit.com/Cosium/vet-brew/6e55c992/1.0/macosx_x64/vet.zip
Error: undefined method `chomp' for nil:NilClass
Please report this bug:
  https://github.com/Linuxbrew/brew/blob/master/docs/Troubleshooting.md#troubleshooting
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/dev-cmd/create.rb:89:in `__gets'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/dev-cmd/create.rb:61:in `create'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/brew.rb:100:in `<main>'
Formula name [vet]:
```

**Comment by reda-alaoui** [comment]
Adding `-ti` option to Docker solves the issue.
Sorry :)

**Comment by sjackman** [comment]
No worries, Réda. Glad that you got it working.
